"""create all

Revision ID: 04390adc6a64
Revises:
Create Date: 2024-12-26 03:33:57.780097

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04390adc6a64"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adress", sa.String(), nullable=False),
        sa.Column("bandwith", sa.Float(), nullable=False),
        sa.Column("energy", sa.Float(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_request_adress"),
        "wallet_request",
        ["adress"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wallet_request_id"), "wallet_request", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_request_id"), table_name="wallet_request")
    op.drop_index(
        op.f("ix_wallet_request_adress"), table_name="wallet_request"
    )
    op.drop_table("wallet_request")
    # ### end Alembic commands ###
